- name: PLAY-1
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.debug:
      msg: "Hello Ansible from PLAY-1"
- name: PLAY-2
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.debug:
      msg: "Hello Ansible from PLAY-2"