- name: ping the server
  hosts: web
  vars:
    Course: "DevOps with AWS"
    Trainer: "Sivakumar Reddy"
    Duration: "110 HRS"
  tasks:
  - name: ping the server
    ansible.builtin.debug:
      msg: "Hello I am learning {{Course}}, Duration: {{Duration}}, Trainer: {{Trainer}}"